services:
  postgres:
    restart: always
    image: postgres
    container_name: "${DATABASE_CONTAINER_NAME}"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - database

  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
      - "5001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - database

  php:
    container_name: "php-fpm"
    build:
      context: ./docker/php
      args:
        PHP_VERSION: ${PHP_VERSION}
    environment:
      # Symfony Config
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - MESSENGER_TRANSPORT_DSN=${MESSENGER_TRANSPORT_DSN}
      - APP_DEBUG=${APP_DEBUG}
      - JWT_PASSPHRASE=${JWT_PASSPHRASE}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ${APP_FOLDER}:/var/www
    networks:
      - database

  nginx:
    container_name: "nginx"
    environment:
      HOSTNAME: ${HOSTNAME}
    build:
      context: ./docker/nginx
    volumes:
      - ${APP_FOLDER}:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - database

volumes:
  database-data:
    external: true

networks:
  database:
    external: true

# docker network create database
# docker volume create database-data
