auth_controllers:
  resource:
    path: ../src/Auth/Infrastructure/Symfony/Http/Get
    namespace: App\Auth\Infrastructure\Symfony\Http\Get
  type: attribute

api_login_check:
  path: /api/auth/login

api_refresh_token_check:
  path: /api/auth/token/refresh
