doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '16'

    profiling_collect_backtrace: "%kernel.debug%"
    use_savepoints: true
    types:
      user_id:
        class: App\Auth\Infrastructure\Persistence\Doctrine\Types\UserIdType
      user_email:
        class: App\Auth\Infrastructure\Persistence\Doctrine\Types\UserEmailType
      user_password:
        class: App\Auth\Infrastructure\Persistence\Doctrine\Types\UserPasswordType
      user_created_at:
        class: App\Auth\Infrastructure\Persistence\Doctrine\Types\UserCreatedAtType
      user_updated_at:
        class: App\Auth\Infrastructure\Persistence\Doctrine\Types\UserUpdatedAtType
      user_deleted_at:
        class: App\Auth\Infrastructure\Persistence\Doctrine\Types\UserDeletedAtType
  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    report_fields_where_declared: true
    validate_xml_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      User:
        type: xml
        is_bundle: false
        dir: "%kernel.project_dir%/src/Auth/Infrastructure/Persistence/Doctrine/Mapping"
        prefix: 'App\Auth\Domain'
        alias: User
    controller_resolver:
      auto_mapping: false

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: "%kernel.build_dir%/doctrine/orm/Proxies"
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
